backend:
  name: github
  repo: prakhar-techcrumb/my-website
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

- name: placeholder
    label: Placeholder
    folder: placeholder
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
